[package]
name = "git-pal"
version = "0.1.0-beta"
description = "A Tauri App"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "git_pal_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [
    "macos-private-api",
    "tray-icon",
    "image-png",
] }
tauri-plugin-opener = { workspace = true }
tauri-plugin-single-instance = { version = "2", features = ["deep-link"] }
tauri-plugin-log = "2"
tauri-plugin-deep-link = "2"
tauri-plugin-autostart = "2"
tauri-plugin-updater = "2"
tauri-plugin-global-shortcut = "2"

user-notify = { git = "https://github.com/deltachat/deltachat-desktop" }
keyring = { version = "3", features = [
    "apple-native",
    "windows-native",
    "sync-secret-service",
] }
anyhow = "1.0.100"
redb = "3.1.0"

git-pal-github = { path = "./crates/git-pal-github"}
git-pal-settings = { path = "./crates/git-pal-settings"}

url = { workspace = true }
tokio = { workspace = true }
log = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
ts-rs = { workspace = true }

[workspace.dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2.0.16"
ts-rs = "11.0.1"
log = "0.4"
tokio = { version = "1.47.1", features = ["full"] }
oauth2 = "5.0.0"
url = "2.5.7"
reqwest = { version = "0.12.23", features = ["json"] }
tauri-plugin-opener = "2"

[workspace]
resolver = "3"
members = ["crates/*"]

[profile.dev]
incremental = true

[profile.release]
codegen-units = 1
lto = true 
opt-level = "s" 
panic = "abort" 
strip = true 
