[package]
name = "git-pal-github"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = { workspace = true }
ts-rs = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
log = { workspace = true }
url = { workspace = true }
oauth2 = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
tauri-plugin-opener = { workspace = true }

graphql_client = "0.14.0"
serde_yaml = "0.9.34"