// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Block, Harness } from "./harness";

/**
 * Streamed to the UI while the agent runs.
 */
export type AgentEvent = { "type": "started", conversationId: number, } | { "type": "textDelta", text: string, } | { "type": "block", block: Block, } | { "type": "done", message: AgentMessage, } | { "type": "error", message: string, };

export type AgentMessage = { id: number, conversationId: number, role: Role, blocks: Array<Block>, createdAt: string, };

export type ContextItem = { "type": "pullRequest" } | { "type": "file", path: string, } | { "type": "comment", path: string, 
/**
 * `None` for file comments
 */
line: number | null, author: string, body: string, };

export type Conversation = { id: number, owner: string, repository: string, prNumber: number, title: string, 
/**
 * Sessions only resume with the harness that created them
 */
harness: Harness, sessionId: string | null, createdAt: string, updatedAt: string, };

export type PullRequestKey = { owner: string, repository: string, prNumber: number, };

export type Role = "user" | "assistant";

export type SendMessageRequest = { owner: string, repository: string, prNumber: number, conversationId: number | null, prompt: string, context: Array<ContextItem>, model: string | null, };
