// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphQLResponse<T> = { rate_limit: RateLimit, data: T | null, errors: Array<string> | null, };

export type RateLimit = { limit: number, remaining: number, reset: number, used: number, };

export type RestResponse<T> = { rate_limit: RateLimit, data: T, };
