// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ApiResponse<T> = { rate_limit: RateLimit, data: T, };

export type RateLimit = { limit: number, remaining: number, reset: number, used: number, };
