// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GraphQLResponse<T> = { metadata: Metadata, data: T | null, errors: Array<string> | null, };

export type Metadata = { rate_limit: RateLimit, token_expiration: string | null, };

export type RateLimit = { limit: number, remaining: number, reset: number, used: number, };

export type RestResponse<T> = { metadata: Metadata, data: T, };

export type Token = { value: string, expire_at: string | null, };
