// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./harness";

export type CodeReview = { id: number, owner: string, repository: string, prNumber: number, prTitle: string, branch: string, headSha: string, status: ReviewStatus, summary: string, comments: Array<ReviewComment>, reviewedAt: string, template: TemplateChoice | null, 
/**
 * Harness running the AI review
 */
harness: Harness | null, model: string | null, error: string | null, warning: string | null, cancelled: boolean, reviewed: boolean, };

export type GetSavedReviewRequest = { owner: string, repository: string, prNumber: number, };

export type PullRequestReview = { comments: Array<ReviewComment>, summary: string, };

export type PullRequestSummary = { title: string, branch: string, headSha: string, };

export type ReviewComment = { file: string, 
/**
 * Last line of the range, `None` for a file level comment
 */
line: number | null, 
/**
 * First line of a multi-line range
 */
startLine: number | null, severity: string, comment: string, 
/**
 * AI comment selected to be posted on GitHub, user comments always are
 */
publish: boolean, 
/**
 * Already posted on GitHub
 */
posted: boolean, };

export type ReviewListEntry = { id: number, owner: string, repository: string, prNumber: number, prTitle: string, branch: string, reviewedAt: string, 
/**
 * False while the pull request was only viewed
 */
reviewed: boolean, headSha: string, status: ReviewStatus, commentCount: number, errorCount: number, warningCount: number, harness: Harness | null, model: string | null, };

export type ReviewPullRequestRequest = { owner: string, repository: string, template: TemplateChoice, prNumber: number, 
/**
 * Only review the commits pushed since the last review, keeping its comments
 */
incremental?: boolean, };

export type ReviewStatus = "Todo" | "Done" | "Submitted";

export type ReviewTemplate = { id: number, name: string, content: string, 
/**
 * Regex tested against "owner/repo"
 */
matcher: string | null, isDefault: boolean, 
/**
 * Skills the review must use
 */
skills: Array<string>, position: number, createdAt: string, updatedAt: string, };

export type ReviewTemplateInput = { name: string, content: string, matcher: string | null, isDefault: boolean, skills: Array<string>, };

export type SetFileViewedRequest = { owner: string, repository: string, prNumber: number, filename: string, sha: string, viewed: boolean, };

/**
 * Which instructions a review uses.
 */
export type TemplateChoice = { "type": "auto" } | { "type": "builtIn" } | { "type": "template", id: number, };

export type UpdateReviewCommentsRequest = { owner: string, repository: string, prNumber: number, comments: Array<ReviewComment>, };

export type UpdateReviewStatusRequest = { owner: string, repository: string, prNumber: number, status: ReviewStatus, };

export type ViewedFile = { filename: string, sha: string, };
