// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which endpoint a comment lives under.
 */
export type CommentKind = "inline" | "issue" | "review";

export type DeleteCommentRequest = { owner: string, repository: string, kind: CommentKind, id: number, };

export type EditCommentRequest = { owner: string, repository: string, number: number, kind: CommentKind, id: number, body: string, };

export type InlineComment = { id: number, author: string, path: string, 
/**
 * `None` when the comment is outdated or on the file itself
 */
line: number | null, startLine: number | null, 
/**
 * Whether `line` refers to the new version of the file
 */
onNewSide: boolean, isFileComment: boolean, inReplyToId: number | null, body: string, signedBody: string, createdAt: string, htmlUrl: string, };

export type IssueComment = { id: number, author: string, body: string, signedBody: string, createdAt: string, htmlUrl: string, };

export type PullRequestConversation = { reviews: Array<Review>, comments: Array<IssueComment>, inlineComments: Array<InlineComment>, };

export type Review = { id: number, author: string, 
/**
 * APPROVED, CHANGES_REQUESTED, COMMENTED, DISMISSED or PENDING
 */
state: string, body: string, signedBody: string, submittedAt: string | null, htmlUrl: string, };
