// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Theme } from "./settings";

export type AuthMessage = { msg: string | null, ok: boolean, };

export type Event = { "authenticated": AuthMessage } | { "themeChanged": Theme };
