// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AuthMsg = { "AuthFailed": { msg: string, ok: boolean, } } | { "AuthSuccess": { ok: boolean, } };
