// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SettingValue, Theme } from "./settings";
import type { AppUpdate } from "./updater";

export type AuthPayload = { msg: string | null, ok: boolean, };

export type Event = { "authMessage": AuthPayload } | { "themeChanged": Theme } | { "settingChanged": SettingValue } | { "updateInstalled": AppUpdate };
