// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FeedbackKind = "bug" | "feature_request" | "other";

export type NewFeedback = { email: string, kind: FeedbackKind, body: string, };
