// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FindRepositoriesSearch = { nodes: Array<FindRepositoriesSearchNodes | null> | null, };

export type FindRepositoriesSearchNodes = { "__typename": "App" } | { "__typename": "Discussion" } | { "__typename": "Issue" } | { "__typename": "MarketplaceListing" } | { "__typename": "Organization" } | { "__typename": "PullRequest" } | { "__typename": "Repository" } & Repository | { "__typename": "User" };

export type Repository = { id: string, name: string, url: string, isPrivate: boolean, isInOrganization: boolean, stargazerCount: number, pullRequests: RepositoryPullRequests, hasIssuesEnabled: boolean, hasDiscussionsEnabled: boolean, hasProjectsEnabled: boolean, hasWikiEnabled: boolean, homepageUrl: string | null, issues: RepositoryIssues, discussions: RepositoryDiscussions, owner: RepositoryOwner, };

export type RepositoryDiscussions = { totalCount: number, };

export type RepositoryIssues = { totalCount: number, };

export type RepositoryOwner = { login: string, avatarUrl: string, } & ({ "__typename": "Organization" } | { "__typename": "User" });

export type RepositoryOwnerOn = { "__typename": "Organization" } | { "__typename": "User" };

export type RepositoryPullRequests = { totalCount: number, };

export type ResponseData = { search: FindRepositoriesSearch, };
