// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Content of a message, whatever the harness producing it.
 */
export type Block = { "type": "text", text: string, } | { "type": "toolUse", id: string, name: string, input: unknown, } | { "type": "toolResult", toolUseId: string, content: string, isError: boolean, };

export type Harness = "claude" | "codex" | "cursor" | "antigravity" | "opencode";

export type Model = { id: string, label: string, };

export type Skill = { name: string, description: string, };
