// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type HomepageViewer = { pullRequests: HomepageViewerPullRequests, topRepositories: HomepageViewerTopRepositories, };

export type HomepageViewerPullRequests = { nodes: Array<HomepageViewerPullRequestsNodes | null> | null, };

export type HomepageViewerPullRequestsNodes = { id: string, number: bigint, title: string, url: string, isDraft: boolean, isInMergeQueue: boolean, mergeable: MergeableState, state: PullRequestState, reviewDecision: PullRequestReviewDecision | null, totalCommentsCount: bigint | null, statusCheckRollup: PullRequestStatusCheckRollup | null, autoMergeRequest: PullRequestAutoMergeRequest | null, author: PullRequestAuthor | null, repository: PullRequestRepository, baseRefName: string, headRefName: string, createdAt: string, mergedAt: string | null, };

export type HomepageViewerTopRepositories = { nodes: Array<HomepageViewerTopRepositoriesNodes | null> | null, };

export type HomepageViewerTopRepositoriesNodes = { id: string, name: string, url: string, isPrivate: boolean, isInOrganization: boolean, stargazerCount: bigint, pullRequests: RepositoryPullRequests, hasIssuesEnabled: boolean, hasDiscussionsEnabled: boolean, hasProjectsEnabled: boolean, hasWikiEnabled: boolean, homepageUrl: string | null, issues: RepositoryIssues, discussions: RepositoryDiscussions, owner: RepositoryOwner, };

export type MergeableState = "CONFLICTING" | "MERGEABLE" | "UNKNOWN" | { "Other": string };

export type PullRequest = { id: string, number: bigint, title: string, url: string, isDraft: boolean, isInMergeQueue: boolean, mergeable: MergeableState, state: PullRequestState, reviewDecision: PullRequestReviewDecision | null, totalCommentsCount: bigint | null, statusCheckRollup: PullRequestStatusCheckRollup | null, autoMergeRequest: PullRequestAutoMergeRequest | null, author: PullRequestAuthor | null, repository: PullRequestRepository, baseRefName: string, headRefName: string, createdAt: string, mergedAt: string | null, };

export type PullRequestAuthor = { login: string, url: string, avatarUrl: string, } & ({ "__typename": "Bot" } | { "__typename": "EnterpriseUserAccount" } | { "__typename": "Mannequin" } | { "__typename": "Organization" } | { "__typename": "User" });

export type PullRequestAuthorOn = { "__typename": "Bot" } | { "__typename": "EnterpriseUserAccount" } | { "__typename": "Mannequin" } | { "__typename": "Organization" } | { "__typename": "User" };

export type PullRequestAutoMergeRequest = { enabledAt: string | null, };

export type PullRequestRepository = { owner: PullRequestRepositoryOwner, name: string, url: string, };

export type PullRequestRepositoryOwner = { login: string, } & ({ "__typename": "Organization" } | { "__typename": "User" });

export type PullRequestRepositoryOwnerOn = { "__typename": "Organization" } | { "__typename": "User" };

export type PullRequestReviewDecision = "APPROVED" | "CHANGES_REQUESTED" | "REVIEW_REQUIRED" | { "Other": string };

export type PullRequestState = "CLOSED" | "MERGED" | "OPEN" | { "Other": string };

export type PullRequestStatusCheckRollup = { state: StatusState, commit: PullRequestStatusCheckRollupCommit | null, };

export type PullRequestStatusCheckRollupCommit = { status: PullRequestStatusCheckRollupCommitStatus | null, };

export type PullRequestStatusCheckRollupCommitStatus = { state: StatusState, contexts: Array<PullRequestStatusCheckRollupCommitStatusContexts>, };

export type PullRequestStatusCheckRollupCommitStatusContexts = { state: StatusState, context: string, description: string | null, targetUrl: string | null, };

export type Repository = { id: string, name: string, url: string, isPrivate: boolean, isInOrganization: boolean, stargazerCount: bigint, pullRequests: RepositoryPullRequests, hasIssuesEnabled: boolean, hasDiscussionsEnabled: boolean, hasProjectsEnabled: boolean, hasWikiEnabled: boolean, homepageUrl: string | null, issues: RepositoryIssues, discussions: RepositoryDiscussions, owner: RepositoryOwner, };

export type RepositoryDiscussions = { totalCount: bigint, };

export type RepositoryIssues = { totalCount: bigint, };

export type RepositoryOwner = { login: string, avatarUrl: string, } & ({ "__typename": "Organization" } | { "__typename": "User" });

export type RepositoryOwnerOn = { "__typename": "Organization" } | { "__typename": "User" };

export type RepositoryPullRequests = { totalCount: bigint, };

export type ResponseData = { viewer: HomepageViewer, };

export type StatusState = "ERROR" | "EXPECTED" | "FAILURE" | "PENDING" | "SUCCESS" | { "Other": string };
