// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { JsonValue } from "./serde_json/JsonValue";

export type Job = { jobId: string, kind: JobKind, name: string, status: JobStatus, payload: JsonValue | null, startedAt: number, updatedAt: number | null, error: string | null, };

export type JobKind = "review";

export type JobStatus = "queued" | "running" | "completed" | "failed" | "cancelled";
