// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommitComparison = { status: CompareStatus, aheadBy: number, };

export type CompareCommitsRequest = { owner: string, repository: string, base: string, head: string, };

/**
 * How head relates to base, `Diverged` once the history was rewritten.
 */
export type CompareStatus = "ahead" | "behind" | "diverged" | "identical";

export type DraftReviewComment = { path: string, body: string, 
/**
 * `None` for a file level comment
 */
line: number | null, startLine: number | null, };

export type FileRequest = { owner: string, repository: string, file_path: string, };

export type FileSourceRequest = { owner: string, repository: string, path: string, gitRef: string, };

export type FindWorkflowsRequest = { owner: string, repository: string, };

export type GetPullRequestRequest = { owner: string, repository: string, number: number, };

export type OwnedFilesRequest = { owner: string, repository: string, baseRef: string, files: Array<string>, };

export type PullRequestDetails = { title: string, htmlUrl: string, headRef: string, headSha: string, baseRef: string, 
/**
 * Markdown description, `None` when left empty
 */
body: string | null, changedFiles: number, 
/**
 * GitHub refuses its diff, it comes from a local clone instead
 */
isDiffTooLarge: boolean, };

export type PullRequestDiff = { files: Array<PullRequestFile>, rawDiff: string, totalAdditions: number, totalDeletions: number, totalFiles: number, };

export type PullRequestFile = { sha: string, filename: string, status: string, additions: number, deletions: number, changes: number, patch: string | null, previousFilename: string | null, };

export type ReviewEvent = "COMMENT" | "APPROVE" | "REQUEST_CHANGES";

export type RunWorkflowRequest = { owner: string, repository: string, workflow_id: number, branch: string, variables: Record<string, any>, };

export type SubmitReviewRequest = { owner: string, repository: string, number: number, 
/**
 * Head commit the comment lines refer to
 */
commitId: string, body: string, event: ReviewEvent, comments: Array<DraftReviewComment>, };

export type Workflow = { id: number, node_id: string, name: string, path: string, state: string, created_at: string, updated_at: string, url: string, html_url: string, badge_url: string, };

export type WorkflowInput = { name: string | null, description: string | null, default: string | null, required: boolean | null, type: string | null, };

export type Workflows = { total_count: number, workflows: Array<Workflow>, };
