// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FileRequest = { owner: string, repository: string, file_path: string, };

export type FindWorkflowsRequest = { owner: string, repository: string, };

export type RunWorkflowRequest = { owner: string, repository: string, workflow_id: number, branch: string, variables: Record<string, any>, };

export type Workflow = { id: number, node_id: string, name: string, path: string, state: string, created_at: string, updated_at: string, url: string, html_url: string, badge_url: string, };

export type WorkflowInput = { name: string | null, description: string | null, default: string | null, required: boolean | null, type: string | null, };

export type Workflows = { total_count: number, workflows: Array<Workflow>, };
