// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MergeableState = "CONFLICTING" | "MERGEABLE" | "UNKNOWN" | { "Other": string };

export type PullRequest = { id: string, number: bigint, title: string, url: string, isDraft: boolean, isInMergeQueue: boolean, mergeable: MergeableState, state: PullRequestState, reviewDecision: PullRequestReviewDecision | null, totalCommentsCount: bigint | null, statusCheckRollup: PullRequestStatusCheckRollup | null, autoMergeRequest: PullRequestAutoMergeRequest | null, author: PullRequestAuthor | null, repository: PullRequestRepository, baseRefName: string, headRefName: string, createdAt: string, mergedAt: string | null, };

export type PullRequestAuthor = { login: string, url: string, avatarUrl: string, } & ({ "__typename": "Bot" } | { "__typename": "EnterpriseUserAccount" } | { "__typename": "Mannequin" } | { "__typename": "Organization" } | { "__typename": "User" });

export type PullRequestAuthorOn = { "__typename": "Bot" } | { "__typename": "EnterpriseUserAccount" } | { "__typename": "Mannequin" } | { "__typename": "Organization" } | { "__typename": "User" };

export type PullRequestAutoMergeRequest = { enabledAt: string | null, };

export type PullRequestRepository = { owner: PullRequestRepositoryOwner, name: string, url: string, };

export type PullRequestRepositoryOwner = { login: string, } & ({ "__typename": "Organization" } | { "__typename": "User" });

export type PullRequestRepositoryOwnerOn = { "__typename": "Organization" } | { "__typename": "User" };

export type PullRequestReviewDecision = "APPROVED" | "CHANGES_REQUESTED" | "REVIEW_REQUIRED" | { "Other": string };

export type PullRequestState = "CLOSED" | "MERGED" | "OPEN" | { "Other": string };

export type PullRequestStatusCheckRollup = { state: StatusState, commit: PullRequestStatusCheckRollupCommit | null, };

export type PullRequestStatusCheckRollupCommit = { status: PullRequestStatusCheckRollupCommitStatus | null, };

export type PullRequestStatusCheckRollupCommitStatus = { state: StatusState, contexts: Array<PullRequestStatusCheckRollupCommitStatusContexts>, };

export type PullRequestStatusCheckRollupCommitStatusContexts = { state: StatusState, context: string, description: string | null, targetUrl: string | null, };

export type ResponseData = { search: SearchPullRequestSearch, };

export type SearchPullRequestSearch = { nodes: Array<SearchPullRequestSearchNodes | null> | null, };

export type SearchPullRequestSearchNodes = { "__typename": "App" } | { "__typename": "Discussion" } | { "__typename": "Issue" } | { "__typename": "MarketplaceListing" } | { "__typename": "Organization" } | { "__typename": "PullRequest" } & PullRequest | { "__typename": "Repository" } | { "__typename": "User" };

export type StatusState = "ERROR" | "EXPECTED" | "FAILURE" | "PENDING" | "SUCCESS" | { "Other": string };
