// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Harness } from "./harness";

export type Avatar = { type: AvatarType, color: string, };

/**
 * Shapes shipped by bot-avatars package
 */
export type AvatarType = "clover" | "flower" | "triangle" | "square" | "blob" | "ghost" | "circle" | "drop" | "star" | "droid" | "mech" | "alien" | "hexagon" | "cat" | "cloud" | "pill" | "pebble" | "puddle";

export type Keybind = { showPalette: string, palette: PaletteKeybind, review: ReviewKeybind, };

export type PaletteKeybind = { primaryAction: string, secondaryAction: string, actions: string, review: string, reviewWithTemplate: string, codeSearch: string, help: string, goBack: string, cancel: string, };

/**
 * Repositories the pull request lists, notifications and repository searches cover.
 * Entries are `owner/repo`, or a bare `owner` for all of its repositories.
 */
export type RepositoryFilter = { 
/**
 * Only these when not empty
 */
include: Array<string>, 
/**
 * Never these, even when included
 */
exclude: Array<string>, };

export type ReviewKeybind = { toggleReviews: string, previousFile: string, nextFile: string, refresh: string, toggleViewType: string, toggleSubmit: string, openPullRequest: string, toggleAgent: string, showShortcuts: string, findInDiff: string, findFile: string, };

export type SettingValue = { "theme": Theme } | { "autoUpdate": boolean } | { "monitorPullRequests": boolean } | { "monitorInterval": number } | { "harness": Harness } | { "models": { [key in Harness]?: string } } | { "paletteKeybind": PaletteKeybind } | { "reviewKeybind": ReviewKeybind } | { "avatar": Avatar } | { "repositoryFilter": RepositoryFilter } | { "pullRequestLimit": number };

export type Settings = { theme: Theme, autoUpdate: boolean, monitorPullRequests: boolean, monitorInterval: number, harness: Harness, models: { [key in Harness]?: string }, keybind: Keybind, avatar: Avatar, repositoryFilter: RepositoryFilter, pullRequestLimit: number, };

export type Theme = "system" | "light" | "dark" | "dracula" | "catppuccinMocha" | "catppuccinLatte" | "andromeda" | "deepPurple";
