// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type SettingValue = { "theme": Theme } | { "globalShortcut": string } | { "autoUpdate": boolean } | { "displayRateLimit": boolean } | { "monitorPullRequests": boolean } | { "monitorInterval": number };

export type Settings = { theme: Theme, globalShortcut: string, autoUpdate: boolean, displayRateLimit: boolean, monitorPullRequests: boolean, monitorInterval: number, };

export type Theme = "system" | "light" | "dark";
