// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Component = { id: string, name: string, status: string, created_at: string, updated_at: string, position: bigint, description: string | null, showcase: boolean, start_date: string | null, group_id: string | null, page_id: string, group: boolean, only_show_if_degraded: boolean, };

export type ComponentStatus = { page: Page, components: Array<Component>, };

export type GithubStatus = { page: Page, status: Status, };

export type Page = { id: string, name: string, url: string, time_zone: string, updated_at: string, };

export type Status = { indicator: string, description: string, };
