// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AppUpdate = { body: string | null, 
/**
 * Version used to check for update
 */
current_version: string, 
/**
 * Version announced
 */
version: string, 
/**
 * Update publish date
 */
date: string | null, };
