// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Organization = { login: string, name: string | null, avatarUrl: string, url: string, };

export type ResponseData = { viewer: UserProfileViewer, };

export type UserProfile = { login: string, avatarUrl: string, email: string, url: string, organizations: UserProfileViewerOrganizations, tokenExpireAt: string | null, };

export type UserProfileViewer = { login: string, avatarUrl: string, email: string, url: string, organizations: UserProfileViewerOrganizations, };

export type UserProfileViewerOrganizations = { nodes: Array<UserProfileViewerOrganizationsNodes | null> | null, };

export type UserProfileViewerOrganizationsNodes = { login: string, name: string | null, avatarUrl: string, url: string, };
