/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PaletteRouteRouteImport } from './routes/palette/route'
import { Route as PaletteIndexRouteImport } from './routes/palette/index'
import { Route as PaletteSearchRouteImport } from './routes/palette/search'
import { Route as PalettePullRequestsRouteImport } from './routes/palette/pull-requests'
import { Route as PaletteRepositoryIdRouteImport } from './routes/palette/repository.$id'
import { Route as PalettePullRequestIdRouteImport } from './routes/palette/pull-request.$id'

const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteRouteRoute = PaletteRouteRouteImport.update({
  id: '/palette',
  path: '/palette',
  getParentRoute: () => rootRouteImport,
} as any)
const PaletteIndexRoute = PaletteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PaletteRouteRoute,
} as any)
const PaletteSearchRoute = PaletteSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PaletteRouteRoute,
} as any)
const PalettePullRequestsRoute = PalettePullRequestsRouteImport.update({
  id: '/pull-requests',
  path: '/pull-requests',
  getParentRoute: () => PaletteRouteRoute,
} as any)
const PaletteRepositoryIdRoute = PaletteRepositoryIdRouteImport.update({
  id: '/repository/$id',
  path: '/repository/$id',
  getParentRoute: () => PaletteRouteRoute,
} as any)
const PalettePullRequestIdRoute = PalettePullRequestIdRouteImport.update({
  id: '/pull-request/$id',
  path: '/pull-request/$id',
  getParentRoute: () => PaletteRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/palette': typeof PaletteRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/palette/pull-requests': typeof PalettePullRequestsRoute
  '/palette/search': typeof PaletteSearchRoute
  '/palette/': typeof PaletteIndexRoute
  '/palette/pull-request/$id': typeof PalettePullRequestIdRoute
  '/palette/repository/$id': typeof PaletteRepositoryIdRoute
}
export interface FileRoutesByTo {
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/palette/pull-requests': typeof PalettePullRequestsRoute
  '/palette/search': typeof PaletteSearchRoute
  '/palette': typeof PaletteIndexRoute
  '/palette/pull-request/$id': typeof PalettePullRequestIdRoute
  '/palette/repository/$id': typeof PaletteRepositoryIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/palette': typeof PaletteRouteRouteWithChildren
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/palette/pull-requests': typeof PalettePullRequestsRoute
  '/palette/search': typeof PaletteSearchRoute
  '/palette/': typeof PaletteIndexRoute
  '/palette/pull-request/$id': typeof PalettePullRequestIdRoute
  '/palette/repository/$id': typeof PaletteRepositoryIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/palette'
    | '/settings'
    | '/setup'
    | '/palette/pull-requests'
    | '/palette/search'
    | '/palette/'
    | '/palette/pull-request/$id'
    | '/palette/repository/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/settings'
    | '/setup'
    | '/palette/pull-requests'
    | '/palette/search'
    | '/palette'
    | '/palette/pull-request/$id'
    | '/palette/repository/$id'
  id:
    | '__root__'
    | '/palette'
    | '/settings'
    | '/setup'
    | '/palette/pull-requests'
    | '/palette/search'
    | '/palette/'
    | '/palette/pull-request/$id'
    | '/palette/repository/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PaletteRouteRoute: typeof PaletteRouteRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette': {
      id: '/palette'
      path: '/palette'
      fullPath: '/palette'
      preLoaderRoute: typeof PaletteRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/palette/': {
      id: '/palette/'
      path: '/'
      fullPath: '/palette/'
      preLoaderRoute: typeof PaletteIndexRouteImport
      parentRoute: typeof PaletteRouteRoute
    }
    '/palette/search': {
      id: '/palette/search'
      path: '/search'
      fullPath: '/palette/search'
      preLoaderRoute: typeof PaletteSearchRouteImport
      parentRoute: typeof PaletteRouteRoute
    }
    '/palette/pull-requests': {
      id: '/palette/pull-requests'
      path: '/pull-requests'
      fullPath: '/palette/pull-requests'
      preLoaderRoute: typeof PalettePullRequestsRouteImport
      parentRoute: typeof PaletteRouteRoute
    }
    '/palette/repository/$id': {
      id: '/palette/repository/$id'
      path: '/repository/$id'
      fullPath: '/palette/repository/$id'
      preLoaderRoute: typeof PaletteRepositoryIdRouteImport
      parentRoute: typeof PaletteRouteRoute
    }
    '/palette/pull-request/$id': {
      id: '/palette/pull-request/$id'
      path: '/pull-request/$id'
      fullPath: '/palette/pull-request/$id'
      preLoaderRoute: typeof PalettePullRequestIdRouteImport
      parentRoute: typeof PaletteRouteRoute
    }
  }
}

interface PaletteRouteRouteChildren {
  PalettePullRequestsRoute: typeof PalettePullRequestsRoute
  PaletteSearchRoute: typeof PaletteSearchRoute
  PaletteIndexRoute: typeof PaletteIndexRoute
  PalettePullRequestIdRoute: typeof PalettePullRequestIdRoute
  PaletteRepositoryIdRoute: typeof PaletteRepositoryIdRoute
}

const PaletteRouteRouteChildren: PaletteRouteRouteChildren = {
  PalettePullRequestsRoute: PalettePullRequestsRoute,
  PaletteSearchRoute: PaletteSearchRoute,
  PaletteIndexRoute: PaletteIndexRoute,
  PalettePullRequestIdRoute: PalettePullRequestIdRoute,
  PaletteRepositoryIdRoute: PaletteRepositoryIdRoute,
}

const PaletteRouteRouteWithChildren = PaletteRouteRoute._addFileChildren(
  PaletteRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PaletteRouteRoute: PaletteRouteRouteWithChildren,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
